export const FRIEND_GET_SUCCESS = "FRIEND_GET_SUCCESS";
export const FRIEND_GET_FAILURE = "FRIEND_GET_FAILURE";
export const FRIEND_GET_REQUEST = "FRIEND_GET_REQUEST";
export const MESSAGE_SEND_REQUEST = "MESSAGE_SEND_REQUEST";
export const MESSAGE_SEND_SUCCESS = "MESSAGE_SEND_SUCCESS";
export const MESSAGE_SEND_FAILURE = "MESSAGE_SEND_FAILURE";
export const MESSAGE_GET_REQUEST = "MESSAGE_GET_REQUEST";
export const MESSAGE_GET_SUCCESS = "MESSAGE_GET_SUCCESS";
export const MESSAGE_GET_FAILURE = "MESSAGE_GET_FAILURE";
export const IMAGE_MESSAGE_SEND_REQUEST = "IMAGE_MESSAGE_SEND_REQUEST";
export const IMAGE_MESSAGE_SEND_SUCCESS = "IMAGE_MESSAGE_SEND_SUCCESS";
export const IMAGE_MESSAGE_SEND_FAILURE = "IMAGE_MESSAGE_SEND_FAILURE";
export const SOCKET_MESSAGE = "SOCKET_MESSAGE";
export const UPDATE_FRIEND_MESSAGE = "UPDATE_FRIEND_MESSAGE";
export const RESET_MESSAGE_SEND_SUCCESS = "RESET_MESSAGE_SEND_SUCCESS";
export const SEEN_MESSAGE = "SEEN_MESSAGE";
export const DELIVERED_MESSAGE = "DELIVERED_MESSAGE";
export const UPDATE = "UPDATE";
export const MESSAGE_GET_SUCCESS_CLEAR = "MESSAGE_GET_SUCCESS_CLEAR";
export const SEEN_ALL = "SEEN_ALL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";


